// Package openapi provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Ra3XPbuBH/VzBoZ+6F1ofjuzmr0wefdWk1F8eulSYPicuByJWEKwnwAFC24+H/3gHA",
	"TxEUKUeT6T1ZlLCL3f399gOgX3DA44QzYEri2QuWwRZiYj5ebUD/WXMRE4VnmDL10wX2cEyeaJzGeHY+",
	"mXg4psw+TTysnhOwC2EDAmcevooUVWloFIUgA0ETRTnDMzz5PJ3852yKQtg8ICqR2gJaC86Uhy4nrh+/",
	"AqNq66Ez98+MhFRgD8MTiZMIjD3dpl82TD8zjw7rv9I4VdsTGC/oZquQpCHUTbz48aCRb368vOwL8DXn",
	"IqSMKPhIBCWryIQamBb4jEnugIdJAcRDqUUqQdlGK5kDWV+x8J9A9DeLOCFUQGjdXpM0Uni2JpGEUnTF",
	"eQSEadlfnxIQNAam5vUQvWg33gHb6PBNJ+cXjm0r0UXoZlrh+tTleiV+M5+3Map+Rmsu0A3fgXmYUwGB",
	"XoPmVK+PdfS0iIcTwRMQioLhP6lx968C1niG/zKusmWcp8q45HjmlQHvE8mXZR4OSgD9XQ3BQ9IOzDOv",
	"6f1hBW7MMg/TcLjoItQSMd9RtvElT1noB5xJRZjqU3JjhJZa5roQ6dLl70iUOurHIw3VFnGBdhDxgKpn",
	"7EilNmkYiWG4j+/1ai2Vxr4SlESyT/Z9Gn+wCzMP/5GCVH4SpdJPiCAxKBA+4yL2g3Ddp+lfWvguSuVd",
	"Ifqei/h6/hZnmYcF/JHaJP2sUevbK3e8yRLPVR/cjOwC+jBojcBVhYevfodANVP4fY5LrWr8dLhmyJ6s",
	"l4PTniqI5XBS6H2z0jQiBHnWz+9IIuGeqGbTDHmax6+o6lNnSWdpvLIMfccfQVzJ5zhR/JuV3egq7VTR",
	"XupIylorMfmGPVymm6uRVOzXkkWbm06cbe5gcb9NVcBjmPOYUONBszYLkAln0oRnEHz3hUALub1kKjW7",
	"+GpS0dpUJGPLtEjzwBc5EQYZV1HHwatI88EndUIMU9rkkUNznJNjkLqbvN/vK5HhYBXLeW/0jUlGadtx",
	"rx5aJzqCcnFKXO4EX5EVjTTdT4hMj9qjYOnRdQQ6BzWdFqZqo2+rbmWLfJuyoF6san3vEegqjSJj6IZK",
	"RQNn5Wp221+lorFpDzegtjys6859j3nHMN3dt1uUXOdmDxoDjI+Zh7mtjH5YlsZD4s06mnnYDAcDhR3l",
	"rtQAZYj8uIzR8HmmFWGtWOdvP01rSa4ZruhQd5aKtr0x8jIg/WN36YDWszQSpTxEdrg4NhZGVSFcRGIv",
	"2eoe7uHXYkMRRM9yq+Fel63diLqytzT9HmQaqU5uk0ClJPIFV1ZlWMxfvZ06lygHNnOues1ZjMlHEBCe",
	"zIajz3ZVIawF96hhYK+4HqOm1f514TpCQdHwX3n2qU9oQwczGR5hn50mynG0Z/XHYl3m5aNsj8Ans2g/",
	"F2vB8NojcceBqjsVDpO0FsQ2evvROsiVLio+1BO6Kmu1bhdRBkTY7jmdHG54rmJWb5yU+cCU4MmzHf/9",
	"6tml977GoELHNRc6OtjDCxbknztk08h9L2R/Qnz9iishKA+BfhyGRx8ZmyPoa4vA6zJ/aLoLEx4/BEVo",
	"NHh47OgKnRNpf2LL1LacvsX5sv1E3UNq369Kv/dtw2y7U9TYmnBJFd2ZixDYEPPRxdblvGMQPjT8LuGp",
	"Te4fJjPEuEL/ZfyReWg6QzGJwEPnM7QG+/HSriBJEtGArCIYocXyFv14Pv35hy86ENUQnesxI7kxyOrQ",
	"7jQ0uJ1qTVutGUGf95nMq3fJswF3FQcPJ5VWF2DLild7A8umf7rY5DetZO0TFvpbe2Hu09qN+SH5jnt2",
	"zXYL5kGmw1N7NIQn3UM29mavyypXGD7W+uaRVzOfivZ5lJw2nbI114KKKt1l8CdYoWVCFLq6W5g+KmT+",
	"fmU0HU3MYScBRhKKZ/jNaDJ6Y2ZVtTV4jasUH+fFOOFStXPiWgBRgAiqBNDqGckEArqmEKKAs5DqxXKE",
	"PmyhXKeQdgJR2d8pRtjYKszDIix3bbYACx5I9QsPTeQDrrlqbM6zScuPf5e2jljoj2wz2f67ADw3NU93",
	"vCoCuE4kJVKojWwmvOeTyfezcJkGAUi5TiNURtGQXaZxTMTzkSga0T1+jElg6u/sBW9AucYClQomEUER",
	"lWY8sAK1/U5Jj3dUquZd9lWQt4rvAIN8PQ6D4uQEgLKjIShEvhsIi8LGPx8Mzlg5gXihYXYAhESANO9P",
	"unNtMT8hCv8A1SgQvzwvyksJUCAknn0+8HJ3oesq1V/q1lC86ZrZt2LNGucdjdAixFn28H9eGodC1kmG",
	"sR2OZXcPvYcNlQqE/WeG8gSln6otoA7KCQlSbG7PFrfrPwFbTt/lqxNt1pwC3c172sZwEJOOhtmSKtFD",
	"f1VSmvjd6R97c0jBkxonEaHsbyjYEiFB/f3fH96e/Vx7l2gZmu+V/2MAvv1Nh6SVOOZrV8n8gm9/+4Jt",
	"GCWIXcGZVER4hrdKJXI2HpOEjh5hdSYTokYKlEy/kkcyCng83k3x/mY3hDJklelBNn9tnieUaLxIvbh4",
	"oyfy8j9rzBfamLoFs/E44gGJtlyq2fTycuradA67gXtqDc1NzTdZlj1k/wsAAP//O3Tl6gImAAA=",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}

