// Package openapi provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RaW2/bOBb+KwR3gXlRfEnTwUSLfcjU011jmiZbd9uHNCvQ0rHNWYnUkJQTN9B/H5C6",
	"W9TFTVCgT7FsnsNzzvedC6k8YZ9HMWfAlMTuE5b+DiJiPl5tQf/ZcBERhV1Mmfr5Ajs4Io80SiLsns9m",
	"Do4oy55mDlaHGLKFsAWBUwdfhYqqJDCKApC+oLGinGEXz+7ms/+dzVEA23tEJVI7QBvBmXLQ5cz241dg",
	"VO0cdGb/mZGACuxgeCRRHIKxp9v0y4bpZ+bRYv1XGiVq9wLGC7rdKSRpAHUTL173Gvnq9eXlUIDfcC4C",
	"yoiCT0RQsg5NqIFpgTtMcgccTAog7kstUgnKtlrJAsjmigX/BqK/WUYxoQKCzO0NSUKF3Q0JJZSia85D",
	"IEzL/vYYg6ARMLWoh+hJu/EO2FaHbz47v7BsW4kuAzvTCtfnNtcr8evFoo1R9TPacIGu+R7Mw4IK8PUa",
	"tKB6faSjp0UcHAseg1AUDP9Jjbt/F7DBLv7btMqWaZ4q05LjqVMGfEgkX5Y62C8B9PY1BPukLZinTtP7",
	"fgV2zFIH02C86DLQEhHfU7b1JE9Y4PmcSUWYGlJybYRWWuZNIdKly9uTMLHUjwcaqB3iAu0h5D5VB2xJ",
	"pTZpGIlgvI/v9WotlUSeEpSEckj2fRJ9zBamDv4zAam8OEykFxNBIlAgPMZF5PnBZkjTf7TwbZjI20L0",
	"PRfRm8VbnKYOFvBnkiXpnUZtaK/c8SZLHFt9sDOyC+h+0BqBqwoPX/8Bvmqm8Pscl1rV+Lm/ZsiBrJej",
	"054qiOR4Uuh909I0IgQ56Od3JJbwgahm0wx4ksevqOpza0lnSbTOGPqOP4C4kocoVvzZyq51lbaqaC+1",
	"JGWtlZh8ww4u083WSCr2a8mizc1n1jbXW9xvEuXzCBY8IpQVxHefjkq0ABlzJk2Ujow5ypFypY2GJsMG",
	"tgo1vJ7I8e1jSkWE1MGhRtMjdTh7ZZvg66KYI9hbT/NeLAfL92rRiozZwMi2rXXqblsjJygXI2M2Ks1u",
	"BV+TNQ01wyxJZgnnS6gtgvwSujIQnq/pZWGqNnpeQSm70tuE+fX6UGs1D0DXSRgaQ7dUKupbi0Wzwf0m",
	"FY1MRb4GteNBXXfue8Q75tfuVtmi5CY3e1TnNT6mDuZZMfICUyKGxK2lK3WwacsjdVgqUqkBykh5URmq",
	"8ZNEK9BasU7jYbbWcl0TXdGx7qwUbXtj5KVPhgfe0gGtZ2UkSnkIs7Z+aiyMqkK4iMRRztU9PMKvRYoi",
	"iE5GsYZ7XbZ2I2pL4tL0DyCTUHVSnPgqIaEnuMpUBsXkMxSbD7lEOSqZE823nIKYfAABwYvZcPKpqqqH",
	"teA+p3Gfosbaw09QULTzbzx11Iei3lAX60zTOsG+lZl/y0FwYPWnYl3q5EPkgMBns+g4F2vBcNrDaMdR",
	"pjsV+klaC2IbveNo9XKli4r39YSuylqt6YWUARFZE53P+vuerZjV+ydlHjAleHzIBm+verbp/VBjUKHj",
	"DRc6OtjBS+bnnztkk9B+I5P9hPjmGy5joDx+eVEQnHxY+xGmd2HC4wWgCA1Hz5AdXaFzMB1ObJlkLWdo",
	"cb7sOFGPkDr2q9LvPG+mbXeKGltjLqmie3MFAVtiPtrYulp0zMN9M/AKHtvk/mnmIsYV+j/jD8xBcxdF",
	"JAQHnbtoA9nHy2wFieOQ+mQdwgQtVzfo9fn8l5++6EBUs3Sux0zmxqBMh3anocHuVGvaas0I+qTNZF69",
	"S56NuCXoPaNUWm2ArSpeHQ0s2+HpYpvfcZKNR1jg7bKrao/W7qr75DtuuDXbMzB7mQ6P7dEQHnUP2WZ3",
	"al1W2cLwqdY3T7wU+Vy0z5PktOmUbbi5JKFKdxn8GdZoFROFrm6Xpo8Kmb/ZmMwnM3PmiYGRmGIXv5rM",
	"Jq/MrKp2Bq9pleLTKAimxDf55T7hLShb2VeJYBIRFFJpyn8mgCo1coI+7qovFNI+ICqHG8UEG1OFeVgG",
	"2MXvqFTNW8IrPy8FRVM3XpzPZvqPzzVpjdl5WmlN0z9kVlAyDozvN+ZW0oS8GYRV4vsg5SYJUWmuIZVM",
	"ooiIw9g4GZljACg7GYJC5LuBsCxs/PFgsMbKCsQTDdIeEGIB0txMk5oqtD4gGYNPNxQCtFy8IAr/AtWY",
	"hH49LMtDJygQErt3Pa/NlgusKwd2TeoX7xDc7H1DVQyVSMA5GaGlPm7ffxcyPIcL4yDrJMM0G36MczGX",
	"VlZsqVQgstfE5YSsn6otoA7KCxKk2DybHW82PwBbzHuuX3lweDGiVCeWtNnltalpi6HzNoajmHQyzBmp",
	"Yj3UVSWlid+t/nEwhxQ8qmkcEsr+gfwdERLUP//78e3ZL7W3NBlD873yV6745ncdklbimK9tJfMLvvn9",
	"C87CKEHsC84kIsQu3ikVS3c6JTGdPMD6TMZETRQomXwlD2Ti82i6n+Pjza4JZShTpgeV/IVknlCi8Yrq",
	"4uKVnrjK/1kwX2hj6ha402nIfRLuuFTu/PJybtt0AfuRe2oNzU3NN2ma3qd/BQAA///DFD3DXCMAAA==",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}

