// Package openapi provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RaW3PbuBX+Kxi0M/tC6+I4O2t2+uC1Nq1m48S10uQhcTkQeSRhSwJcAJTtePjfOwDv",
	"IniRo8mkTxYlnINzzvedC0A/Y59HMWfAlMTuM5b+DiJiPl5tQf/ZcBERhV1Mmfr5Ajs4Io80SiLsns9m",
	"Do4oy55mDlZPMWQLYQsCpw6+ChVVSWAUBSB9QWNFOcMunn2ez/5zNkcBbO8RlUjtAG0EZ8pBlzPbj1+B",
	"UbVz0Jn9Z0YCKrCD4ZFEcQjGnm7TLxumn5lHi/VfaZSo3QmMF3S7U0jSAOomXrzuNfLV68vLoQBfcy4C",
	"yoiCj0RQsg5NqIFpgc+Y5A44mBRA3JdapBKUbbWSBZDNFQv+CUR/s4xiQgUEmdsbkoQKuxsSSihF15yH",
	"QJiW/e0xBkEjYGpRD9GzduMtsK0O33x2fmHZthJdBnamFa7Pba5X4jeLRRuj6me04QLd8D2YhwUV4Os1",
	"aEH1+khHT4s4OBY8BqEoGP6TGnf/KmCDXfyXaZUt0zxVpiXHU6cM+JBIvix1sF8C6O1rCPZJWzBPnab3",
	"/QrsmKUOpsF40WWgJSK+p2zrSZ6wwPM5k4owNaTkxgittMx1IdKly9uTMLHUjwcaqB3iAu0h5D5VT9iS",
	"Sm3SMBLBeB/f6dVaKok8JSgJ5ZDsuyT6kC1MHfxnAlJ5cZhILyaCRKBAeIyLyPODzZCmf2nh2zCRt4Xo",
	"Oy6i68UbnKYOFvBnkiXpZ43a0F65402WOLb6YGdkF9D9oDUCVxUevv4DfNVM4Xc5LrWq8XN/zZADWS9H",
	"pz1VEMnxpND7pqVpRAjypJ/fkljCHVHNphnwJI9fUdXn1pLOkmidMfQtfwBxJZ+iWPFvVnajq7RVRXup",
	"JSlrrcTkG3ZwmW62RlKxX0sWbW4+s7a53uL+PlE+j2DBI0KNB83aLEDGnEkTnlHw3RUCLeQOkqnUbOOr",
	"ScXMpiIZW6aFmgeeyIkwyriKOhZehZoPHqkTYpzSJo8smqOcHKPU3eT9/lCJDEarWC0Go29MMkrbjjv1",
	"0FrREZSLU+JyK/iarGmo6X5CZAbUHgXLgK4j0OnVdFqYqo2+rbqVLfJNwvx6sar1vQeg6yQMjaFbKhX1",
	"rZWr2W1/k4pGpj3cgNrxoK479z3iHcN0d99uUXKTmz1qDDA+pg7mWWX0grI09ok362jqYDMcjBS2lLtS",
	"A5Qh8qIyRuPnmVaEtWKdv8M0rSW5ZriiY91ZKdr2xshLnwyP3aUDWs/KSJTyEGbDxbGxMKoK4SISB8lW",
	"9/AAvxYbiiA6Gbca7nXZ2o2oLXtL0+9AJqHq5DbxVUJCT3CVqQyK+WuwU+cS5cBmzlUvOYsx+QACgpPZ",
	"cPTZriqEteAeNQwcFNdj1LTavy5cRygoGv4Lzz71CW3sYCaDI+zLpolyHB1Y/bFYlzr5KDsg8MksOszF",
	"WjCc9kjccaDqToV+ktaC2EbvMFq9XOmi4n09oauyVut2IWVARNY957P+hmcrZvXGSZkHTAkeP2Xjv1c9",
	"2/Te1RhU6LjmQkcHO3jJ/Pxzh2wS2u+Fsp8Q37zgSgjKQ6AXBcHRR8bmCPrSIvCyzB+b7sKExwtAERqO",
	"Hh47ukLnRDqc2DLJWs7Q4nzZYaIeIHXoV6Xf+bZhtt0pamyNuaSK7s1FCGyJ+Whj62rRMQj3Db8reGyT",
	"+6eZixhX6L+MPzAHzV0UkRAcdO6iDWQfL7MVJI5D6pN1CBO0XL1Hr8/nv/z0RQeisH6GHTzHDj7HDr60",
	"290aqFpjgD7SM5kX6JJKI64jes8flVYbJquKOgczyXZ4gNjml6lk4xEWeLvsTtyjtUvxPvmOq3RN6Ayv",
	"XjLDY3v6g0fdJrbZ5V2XVbYwfKy1xiNvXz4VHfIoOW06ZRuuBRVVupHgT7BGq5godHW7NK1SyPwVymQ+",
	"mZnzTAyMxBS7+NVkNnllxlG1M3hNqyye5vU25lK1aX8tgChABFUCaP2EZAw+3VAIkM9ZQPViOUEfdlCu",
	"U0g7gagcbgYTbGwV5mEZlLs2q3wGHkj1Kw9M5H2uuWpszlNOy0//kFmpyKA/spOkh9f9eGHKmm5qVQRw",
	"nUhKJFCbykx4z2ez72fhKvF9kHKThKiMoiG7TKKIiKcjUTSiB/yYEt+UWPcZb0HZOr9KBJOIoJBKMwFk",
	"ArX9TkmPt1Sq5nX1lZ93g+8Ag3w5DqPiZAWAsqMhKES+GwjLwsb/PxissbIC8UyDtAeEWIA0r0i6c225",
	"OCEK/wDVKBC/Pi3LewdQICR2P/e8v13qukr1l7o1FC+z3OzFV7PGOUcjtAxwmt7/4KVxLGSdZJhm86/s",
	"7qF3sKVSgcj+X6E8JOmnaguog3JCghSbN2KVnSV+TK6cvsdXR9a0OQPaW/e8jeAoHh0NckapWI/8VUFp",
	"onerfxzMIAWPahqHhLK/IX9HhAT1939/eHP2S+1lYcbPfK/8zT9+/7sOSSttzNe2gvkFv//9C87CKEHs",
	"C84kIsQu3ikVS3c6JTGdPMD6TMZETRQomXwlD2Ti82i6n+PDzW4IZShTpsfY/L14nk6i8ab04uKVnsfL",
	"f50xX2hj6ha402nIfRLuuFTu/PJybtt0AfuRe2oNzU3NN2ma3qf/CwAA//8AHl9N4yUAAA==",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
