name: ci_backend
on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.x

      - name: Test backend
        run:  cd ./backend/; go test ./... -v

